version: '3.1'
services:
  mongo:
    container_name: mongo
    image: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - "./backend/mongodb:/data/db"

  todo-backend:
    container_name: todo-backend
    build: ./backend
    image: todo-backend:latest
    restart: always
    ports:
      - 15000:15000
    volumes:
      - "./backend:/app"
    depends_on:
      - mongo

  todo-frontend:
    container_name: todo-frontend
    build: ./frontend
    image: todo-frontend:latest
    restart: always
    ports:
      - 3000:3000
    volumes:
      - "./frontend:/app"
    depends_on:
      - todo-backend

  