name: Docker Compose CI

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: sorasit6610545944
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build images via Docker Compose
        run: docker compose -f docker-compose.yml build

      - name: Push backend image
        run: docker push sorasit6610545944/todo-backend:latest

      - name: Push frontend image
        run: docker push sorasit6610545944/todo-frontend:latest
